"""Markdown report generator.

Converts an execution trace, phrased answer, and optional overlay
references into a downloadable Markdown report.

Public API
----------
generate_report(trace, phrased_answer, overlay_refs) -> str
"""

from __future__ import annotations

from typing import Any


def generate_report(
    trace: dict[str, Any],
    phrased_answer: str,
    overlay_refs: list[str] | None = None,
) -> str:
    """Generate a Markdown report from pipeline outputs.

    Parameters
    ----------
    trace : dict
        Execution trace dict as returned by ``execution_trace.build_trace``.
    phrased_answer : str
        Natural-language answer produced by the phrasing layer.
    overlay_refs : list[str] | None
        Optional list of file paths to overlay/visualisation images.

    Returns
    -------
    str
        Complete Markdown document as a string.
    """
    lines: list[str] = []

    # Header
    lines.append("# SatQuery AI — Analysis Report")
    lines.append("")
    lines.append(f"**Generated:** {trace.get('timestamp', 'N/A')}")
    lines.append("")

    # Task summary
    lines.append("## Task")
    lines.append("")
    lines.append(f"- **Type:** `{trace.get('task', 'N/A')}`")
    lines.append(f"- **Confidence:** {trace.get('confidence', 'N/A')}")
    lines.append("")

    # Tools invoked
    tools = trace.get("tools_invoked", [])
    if tools:
        lines.append("## Tools Invoked")
        lines.append("")
        lines.append("| # | Tool |")
        lines.append("|---|------|")
        for idx, tool in enumerate(tools, start=1):
            lines.append(f"| {idx} | `{tool}` |")
        lines.append("")

    # Parameters
    parameters = trace.get("parameters", {})
    if parameters:
        lines.append("## Parameters")
        lines.append("")
        lines.append("| Key | Value |")
        lines.append("|-----|-------|")
        for key, value in parameters.items():
            lines.append(f"| `{key}` | {value} |")
        lines.append("")

    # Answer
    lines.append("## Answer")
    lines.append("")
    lines.append(phrased_answer)
    lines.append("")

    # Overlays
    if overlay_refs:
        lines.append("## Visualisations")
        lines.append("")
        for ref in overlay_refs:
            lines.append(f"![Overlay]({ref})")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(
        "*Report generated by SatQuery AI. "
        "See the execution trace JSON for full audit details.*"
    )
    lines.append("")

    # TODO: PDF stretch goal — convert Markdown to PDF via weasyprint or similar.

    return "\n".join(lines)
